name: gesi
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.3.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.5
  - colorama=0.4.4
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - icu=58.2
  - importlib-metadata=3.10.0
  - importlib_metadata=3.10.0
  - intel-openmp=2021.2.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jdcal=1.4.1
  - jedi=0.17.0
  - jinja2=3.0.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyter_http_over_ws=0.0.8
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.0.1
  - mistune=0.8.4
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - msys2-conda-epoch=20160418
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - notebook=6.4.0
  - numpy=1.20.2
  - numpy-base=1.20.2
  - openpyxl=3.0.5
  - openssl=1.1.1k
  - packaging=21.0
  - pandas=1.2.5
  - pandocfilters=1.4.3
  - parso=0.8.2
  - pickleshare=0.7.5
  - pip=21.1.3
  - ply=3.11
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.17
  - prompt_toolkit=3.0.17
  - pycparser=2.20
  - pygments=2.9.0
  - pyomo=6.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.7.10
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2021.1
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=5.1.0
  - qtpy=1.9.0
  - send2trash=1.5.0
  - setuptools=52.0.0
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.36.0
  - terminado=0.9.4
  - testpath=0.5.0
  - tornado=6.1
  - traitlets=5.0.5
  - typing_extensions=3.10.0.0
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wincertstore=0.2
  - winpty=0.4.3
  - zeromq=4.3.3
  - zipp=3.5.0
  - zlib=1.2.11
  - pip:
    - cplex==20.1.0.0
